version: '3.8'

services:
  weather-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3023:3023"
    environment:
      - NEXT_PUBLIC_OPENWEATHER_API_KEY=4c16ffa8df277ffbc8eb902919682541
      - NODE_ENV=production
      - PORT=3023
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3023/api/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
